src/Entity/Message.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MessageRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Message
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups({"messages"})
     */
    private $id;


    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     * @Groups({"messages"})
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     * @Groups({"messages"})
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @Groups({"messages"})
     */
    private $read_at;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="messages")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\ManyToMany(targetEntity=Chat::class, inversedBy="messages")
     */
    private $chat;




    /**
     * Message constructor.
     */
    public function __construct()
    {
        $this->read_at = null;
        $this->chat = new ArrayCollection();
    }



    public function getId()
    {
        return $this->id;
    }



    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }


    /**
     * @ORM\PrePersist
     */
    public function setCreatedAt()
    {
        $datetime = new \DateTime('now');
        $timezone = new \DateTimeZone('Europe/Moscow');
        $datetime->setTimezone($timezone);
        $this->created_at = $datetime;
    }

    public function getReadAt(): ?\DateTimeInterface
    {
        return $this->read_at;
    }

    public function setReadAt(?\DateTimeInterface $read_at): self
    {
        $this->read_at = $read_at;

        return $this;
    }



    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Chat[]
     */
    public function getChat(): Collection
    {
        return $this->chat;
    }

    public function addChat(Chat $chat): self
    {
        if (!$this->chat->contains($chat)) {
            $this->chat[] = $chat;
        }

        return $this;
    }

    public function removeChat(Chat $chat): self
    {
        if ($this->chat->contains($chat)) {
            $this->chat->removeElement($chat);
        }

        return $this;
    }




}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\Chat;
use App\Entity\Filter;
use App\Entity\Product;
use App\Entity\ProductFilter;
use App\Entity\ProductStatuses;
use App\Entity\ProductType;
use App\Entity\User;
use App\Entity\UserIndividual;
use App\Event\NewProductEvent;
use App\EventSubscriber\ProductSubscriber;
use App\Form\ProductFormType;
use App\Form\RegistrationIndividualFormType;
use App\Form\RegistrationLegalFormType;
use App\Repository\CategoryRepository;
use App\Repository\ChatRepository;
use App\Repository\FilterRepository;
use App\Repository\FilterValuesRepository;
use App\Repository\MessageRepository;
use App\Repository\ProductFilterRepository;
use App\Repository\ProductRepository;
use App\Repository\ProductTypeRepository;
use App\Repository\UserIndividualRepository;
use App\Repository\UserLegalRepository;
use App\Repository\UserRepository;
use App\Serializer\Normalizer\StatisticsNormilizerNormalizer;
use App\Service\ProductService;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\Filesystem\Exception\FileNotFoundException;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Finder\Finder;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Address;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\Routing\Generator\UrlGenerator;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Security\Core\Encoder\PasswordEncoderInterface;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\Uid\Uuid;
use Tchoulom\ViewCounterBundle\Finder\StatsFinder;

class DashboardController extends AbstractController
{
    /**
     * @Route("/dashboard", name="dashboard")
     * @IsGranted("ROLE_USER")
     *
     */
    public function index(CategoryRepository $categoryRepository, FilterRepository $filterRepository)
    {

        if ($this->isGranted('ROLE_ADMIN')) {
            return new RedirectResponse('/admin');
        }

        return $this->render('dashboard/index.html.twig', [
            'controller_name' => 'DashboardController',
        ]);
    }

    /**
     * @Route("/messenger/user/{productId}/{id}", name="dashboard_chat")
     * @IsGranted("ROLE_USER")
     *
     */
    public function chat(Request $request, $productId, ChatRepository $chatRepository, EntityManagerInterface $entityManager, UserRepository $userRepository, ProductRepository $productRepository, MessageRepository $messageRepository)
    {
        $channelId = $request->get('id');
        $chat = $chatRepository->findOneBy(['slug' => $channelId]);
        $product = $productRepository->findOneBy(['id' => $productId]);
        $from_user = $this->getUser()->getId();

        if ($chat) {
            if ($chat->getFromUser()->getId() === $this->getUser()->getId()) {
                $to_user = $chat->getToUser()->getId();
            } else {
                $to_user = $chat->getFromUser()->getId();
            }
        } else {
            $chat = new Chat();
            $chat->setSlug($channelId);
            $chat->setFromUser($userRepository->findOneBy(['id' => $this->getUser()->getId()]));
            $chat->setToUser($product->getUser());
            $chat->setProduct($product);
            $entityManager->persist($chat);
            $entityManager->flush();
            $to_user = $product->getUser()->getId();
        }




//        $productId =
        return $this->render('dashboard/chat/index.html.twig', [
            'channelId' => $channelId,
            'productId' => $productId,
            'from_user' => $from_user,
            'to_user' => $to_user,
            'product' => $product
        ]);
    }

    /**
     * @Route("/dashboard/messages", name="dashboard_messages")
     * @IsGranted("ROLE_USER")
     *
     */
    public function messages(Request $request, MessageRepository $messageRepository, ChatRepository $chatRepository)
    {

        $datetime = new \DateTime('now');
        $timezone = new \DateTimeZone('Europe/Moscow');
        $datetime->setTimezone($timezone);


        return $this->render('dashboard/messages.html.twig', [
            'chats' => $chatRepository->getChatByUser($this->getUser()->getId())
        ]);
    }

    /**
     * @Route("/messenger/system/{id}", name="dashboard_admin_chat")
     * @IsGranted("ROLE_USER")
     *
     */
    public function getAdminMessages(Request $request, MessageRepository $messageRepository, ChatRepository $chatRepository)
    {

        $channelId = $request->get('id');
        $chat = $chatRepository->findOneBy(['slug' => $channelId]);
        if ($chat->getFromUser()->getId() === $this->getUser()->getId()) {
            $to_user = $chat->getToUser()->getId();
        } else {
            $to_user = $chat->getFromUser()->getId();
        }

        $from_user = $this->getUser()->getId();



//        $productId =
        return $this->render('dashboard/chat/index.html.twig', [
            'channelId' => $channelId,
            'productId' => null,
            'system' => true,
            'from_user' => $from_user,
            'to_user' => $to_user
        ]);
    }

    /**
     * @Route("/dashboard/system/messages", name="dashboard_system_messages")
     * @IsGranted("ROLE_USER")
     *
     */
    public function messagesFromAdmin(Request $request, MessageRepository $messageRepository, ChatRepository $chatRepository)
    {

        $datetime = new \DateTime('now');
        $timezone = new \DateTimeZone('Europe/Moscow');
        $datetime->setTimezone($timezone);




        return $this->render('dashboard/messages.html.twig', [
            'chats' => $chatRepository->getChatByAdmin($this->getUser()->getId())
        ]);
    }

    /**
     * @Route("/dashboard/pay", name="dashboard_payment")
     * @IsGranted("ROLE_USER")
     *
     */
    public function pay(Request $request, ProductRepository $productRepository)
    {
        $products = $productRepository->findBy(['status' => ProductStatuses::STATUS_ACTIVE, 'is_premium' => false]);
        return $this->render('dashboard/payment.html.twig', [
            'products' => $products
        ]);
    }

    /**
     * @Route("/dashboard/statistics", name="dashboard_statistics")
     * @IsGranted("ROLE_USER")
     *
     */
    public function statistics(Request $request,StatisticsNormilizerNormalizer $statisticsNormilizerNormalizer, StatsFinder $statsFinder, Security $security, ProductRepository $productRepository){
        $products = $productRepository->findBy(['user' => $security->getUser()->id]);
        $weekNumber = (new \DateTime('now'))->format('W');
        $monthNumber = (new \DateTime('now'))->format('m');
        $year = (new \DateTime('now'))->format('Y');
        $day = (new \DateTime('now'))->format('l');

        $statistics = [];
        foreach ($products as $product) {
            $statisticsData = $statsFinder->getDailyStats($product, $year, $monthNumber, $weekNumber);
            if ($statisticsData) {
                $statistics[$product->getId()] = $statisticsNormilizerNormalizer->normalize($statisticsData, null, ['day' => $day]);
            }
       }



        return $this->render('dashboard/statistics.html.twig', [
            'products' => $products,
            'statistics' => $statistics
        ]);
    }

    /**
     * @Route("/dashboard/subscribe", name="dashboard_subscribe")
     * @IsGranted("ROLE_USER")
     *
     */
    public function subscribe(Request $request)
    {
        return $this->render('dashboard/subscribe.html.twig', [

        ]);
    }

    /**
     * @Route("/dashboard/add", name="dashboard_add")
     * @IsGranted("ROLE_USER")
     *
     */
    public function add(Request $request,ProductService $productService,
                        UserPasswordEncoderInterface $userPasswordEncoder,
                        EntityManagerInterface $entityManager,
                        FilterRepository $filterRepository,
                        SluggerInterface $slugger,
                        CategoryRepository $categoryRepository,
                        Filesystem $filesystem, UserRepository $userRepository,
                        FilterValuesRepository $filterValuesRepository,
                        ProductFilterRepository $productFilterRepository,
                        ParameterBagInterface $parameter,
                        Security $security,
                        EventDispatcherInterface $dispatcher,
                        ProductSubscriber $productSubscriber
    )
    {

        if ($this->isGranted('ROLE_ADMIN')) {
            return $this->redirectToRoute('admin');
        }


        $product = new Product();
        $form = $this->createForm(ProductFormType::class,$product);
        $form->handleRequest($request);



        if (!$form->isSubmitted()) {
            $productService->clearTempDir();
        }
        // Добавление своих категорий






        if ($form->isSubmitted() && $form->isValid()){

            $newCategory = null;
            if ($request->request->get('new_category_parent')){
               $newCategory['parent'] = $request->request->get('new_category_parent');
               $newCategory['name'] = $request->request->get('new_category_name');

templates/dashboard/add.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Личный кабинет{% endblock %}

{% block content %}
    {% include 'partials/preview.html.twig' %}
<ul class="breadcrumbs">
    <li><a href="#">Главная</a><span class="delimeter"></span></li>
    <li class="active"><a href="#">Добавить объяыление</a><span class="delimeter"></span></li>
</ul>
<div class="user__section">
    {% include 'dashboard/sidebar.html.twig' %}
    <section class="make-form">
        <h1 class="make-form__title">Создать объявление</h1>

        {% if app.flashes('success') %}


                <div class="alert alert-success">
                    Ваше объявление передано на модерацию

                </div>

        {% else %}
        <div class="row">
            {{ form_errors(form) }}
        </div>
        {{ form_start(form, {'attr': {'class': 'make-form__inner'}}) }}

        {% do form.category.setRendered() %}
        {% do form.filter.setRendered() %}
        {% do form.type.setRendered() %}
            <div id="categoriesComponent">
                <categories></categories>

            </div>
            <div>
                <div class="make-form__wrapper" id="imageInputComponent">
                    <div class="make-form__header">
                        <div class="w-100" >
                         {{ form_label(form.name) }}
                            {{ form_widget(form.name) }}
                        </div>


                        <image-input image-count="4" image-form-props-data="{{ { 'wrapperClass'  : 'make-form__photos-block', 'name' : 'product_form[photo][]', 'required' : 'true'}|json_encode }}"></image-input>
{#                        <div class="make-form__photos">#}

{#                            <label class="filters__label" for="name">Фото</label>#}
{#                            {{ form_errors(form.photo) }}#}
{#                            <div class="make-form__photos-block">#}
{#                                <label class="input-file-label active"#}
{#                                                                        for="{{ form.photo.vars.id }}"></label>#}
{#                                {{ form_widget(form.photo) }}#}
{#                                <input#}
{#                                        class="input-file" type="file" id="photo1">#}
{#                                <label#}
{#                                        class="input-file-label" for="{{ form.photo.vars.id }}">+</label><input class="input-file"#}
{#                                                                                             type="file"#}
{#                                                                                             id="photo2">#}
{#                        <label>#}
{#                                        class="input-file-label" for="{{ form.photo.vars.id }}">+</label><input class="input-file"#}
{#                                                                                             type="file"#}
{#                                                                                             id="photo3"><label#}
{#                                        class="input-file-label" for="{{ form.photo.vars.id }}">+</label><input class="input-file"#}
{#                                                                                             type="file"#}
{#                                                                                             id="photo4"><label#}
{#                                        class="input-file-label" for="{{ form.photo.vars.id }}">+</label><input class="input-file"#}
{#                                                                                             type="file"#}
{#                                                                                             id="photo5">#}
{#                            </div>#}
{#                        </div>#}
                    </div>
                    <div style="width:100%">
                    {{ form_label(form.description) }}
                    {{ form_widget(form.description) }}
                    </div>
                    <div class="make-form__footer" id="inputWithSeparator">
                        {% do form.price.setRendered() %}
                        <input-with-separator name="{{ form.price.vars.full_name }}" placeholder="{{ form.price.vars.attr.placeholder }}"></input-with-separator>
                        {{ form_errors(form.address) }}
                        {{ form_widget(form.address) }}
                    </div>
                </div>
                <div class="make-form__bottom"><p><span class="color-red">*</span>Обязательные поля</p>
                    <button class="btn-primary">Отправить на модерацию</button>
                </div>
            {{ form_end(form) }}
        </div>
        {% endif %}
    </section>
</div>
{% endblock %}

templates/dashboard/edit.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Личный кабинет{% endblock %}

{% block content %}
    {% include 'partials/preview.html.twig' %}
    <ul class="breadcrumbs">
        <li><a href="#">Главная</a><span class="delimeter"></span></li>
        <li class="active"><a href="#">Добавить объяыление</a><span class="delimeter"></span></li>
    </ul>
    <div class="user__section">
        {% if is_granted("ROLE_ADMIN") %}
            {% include 'dashboard/sidebar-admin.html.twig' %}
        {% else %}
             {% include 'dashboard/sidebar.html.twig' %}
        {% endif %}
        <section class="make-form">
            <h1 class="make-form__title">Редактировать объявление</h1>
            <div class="row">
                {{ form_errors(form) }}
            </div>
            {{ form_start(form, {'attr': {'class': 'make-form__inner'}}) }}
            {% if is_granted('ROLE_ADMIN') %}
            <div class="admin-form__wrapper">
                <div>
                    {{ form_label(form.status) }}
                    {{ form_widget(form.status) }}
                </div>
                <div>
                    {{ form_label(form.reason) }}
                    {{ form_widget(form.reason) }}
                </div>
            </div>
            {% endif %}
            {% do form.category.setRendered() %}
            {% do form.type.setRendered() %}
            {% do form.filter.setRendered() %}
            <div id="categoriesComponent">

                 <categories form-name="{{ form_name }}" selected-type="{{ product.type.values[0].id }}" category-data="{{ categoryData|json_encode() }}"></categories>
                <div class="color-red" style="margin-top: 10px">{{ form_errors(form.type) }}</div>
            </div>

            <div>
                <div class="make-form__wrapper">
                    <div class="make-form__header" id="imageInputComponent">
                        <div>
                            <label class="filters__label" for="name">Описание</label>
                            {{ form_widget(form.name) }}
                        </div>
                            <image-input image-count="4" images="{{ imageData|json_encode }}" product-id="{{ product.id }}"
                                         image-form-props-data="{{ { 'wrapperClass'  : 'make-form__photos-block', 'name' : 'product_form[photo][]','required' : 'false' }|json_encode }}"

                            ></image-input>
                    </div>
                    {{ form_widget(form.description) }}
                    <div class="make-form__footer">
                        {{ form_errors(form.price) }}
                        {{ form_widget(form.price) }}
                        {{ form_errors(form.address) }}
                        {{ form_widget(form.address) }}
                    </div>
                </div>
                <div class="make-form__bottom"><p><span class="color-red">*</span>Обязательные поля</p>
                    {% if is_granted('ROLE_ADMIN') %}
                        <button class="btn-primary">Сохранить</button>
                    {% else %}
                    <button class="btn-primary">Отправить на модерацию</button>
                    {% endif %}
                </div>
                {{ form_end(form) }}
            </div>
        </section>
    </div>

    <script>
        const select = document.querySelector('#product_form_status');
        const textarea = document.querySelector('#product_form_reason').parentElement;
        if (Number(select.value) !== 3) {
            textarea.classList.add('hidden')
        }
        select.addEventListener('change',(evt) => {
            if (Number(evt.target.value) !== 3) {
                textarea.classList.add('hidden')
            } else {
                textarea.classList.remove('hidden')
            }
        });
    </script>
{% endblock %}

templates/dashboard/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Личный кабинет{% endblock %}

{% block content %}
    {% include 'partials/preview.html.twig' %}
    <ul class="breadcrumbs">
        <li><a href="#">Главная</a><span class="delimeter"></span></li>
        <li class="active"><a href="#">Личный кабинет</a><span class="delimeter"></span></li>
    </ul>
    <div class="user__section">
        {% include 'dashboard/sidebar.html.twig' %}
        <section><p class="user__title title-underline"><span>Добро пожаловать</span></p>
            <p class="user__text">
                Вы находитесь в вашем личном кабинете проекта Algroo.com. Algroo.com - это платформа объявлений по всему миру. Вы можете создать свое объявление и рассказать о своем продукты миллионам наших пользователей по всему миру.
                <br> Желаем вам отлично дня и чудесного настроения!</p>
            <div class="user-menu">
                <div class="user-menu__item">
                    <ul class="list">
                        <li class="list__item"><a href="{{ path('dashboard_products') }}">Мои объявления<i
                                        class="material-icons">create</i></a>
                            <ul class="sublist">
                                <li class="sublist__item"><a href="{{ path('dashboard_products') }}">- Редактировать
                                        объявления</a></li>
                                <li class="sublist__item"><a href="{{ path('dashboard_statistics') }}">- Статистика объявлений</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="user-menu__item">
                    <ul class="list">
                        <li class="list__item"><a href="{{ path('dashboard_add') }}">Создать новое объявление</a>
                            <ul class="sublist">
                                <li class="sublist__item"><a href="{{ path('dashboard_add') }}">- Создать объявление</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="user-menu__item">
                    <ul class="list">
                        <li class="list__item"><a href="{{ path('dashboard_messages') }}">Сообщения от пользователей</a>
                            <ul class="sublist">
                                <li class="sublist__item"><a href="{{ path('dashboard_messages') }}">- Входящие</a></li>
                                <li class="sublist__item"><a href="#">- Исходящие</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="user-menu__item">
                    <ul class="list">
                        <li class="list__item"><a href="{{ path('dashboard_payment') }}">Применить пакет платных услуг</a>
                            <ul class="sublist">
                                <li class="sublist__item"><a href="/payment-lk.html">- Преимум размещение</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="user-menu__item">
                    <ul class="list">
                        <li class="list__item"><a href="{{ path('dashboard_subscribe') }}">Подписка</a>
                            <ul class="sublist">
                                <li class="sublist__item"><a href="{{ path('dashboard_subscribe') }}">- Создать подписку</a></li>
                                <li class="sublist__item"><a href="/subscribe.html">- Мои подписки</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="user-menu__item">
                    <ul class="list">
                        <li class="list__item"><a href="/shop.html">Создать карточку
                                магазина<span>(Для Юр.лиц.)</span></a></li>
                    </ul>
                </div>
                <div class="user-menu__item">
                    <ul class="list">
                        <li class="list__item"><a href="#">Сообщения от системы</a>
                            <ul class="sublist">
                                <li class="sublist__item"><a href="#">- Входящие</a></li>
                                <li class="sublist__item"><a href="#">- Исходящие</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="user-menu__item">
                    <ul class="list">
                        <li class="list__item"><a href="#">Личные данные<i class="material-icons">create</i></a>
                            <ul class="sublist">
                                <li class="sublist__item"><a href="#">- Редактировать</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </section>
{% endblock %}

templates/dashboard/products.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Личный кабинет{% endblock %}

{% block content %}
    {% include 'partials/preview.html.twig' %}
    <ul class="breadcrumbs">
        <li><a href="#">Главная</a><span class="delimeter"></span></li>
        <li class="active"><a href="#">Добавить объяыление</a><span class="delimeter"></span></li>
    </ul>
    <div class="user__section">
        {% include 'dashboard/sidebar.html.twig' %}
        <section class="make-form">
            <h1 class="make-form__title">Мои объявления</h1>
            <div class="block__wrapper">
                <table class="preview-table">
                    <thead>
                    <tr class="product-table__row">
                        <td>Название объявления</td>
                        <td>Дата создания</td>
                        <td>Обновлено (дн.)</td>
                        <td>Статус</td>
                        <td>Редактировать</td>
                    </tr>
                    </thead>
                    <tbody>

                    {% for product in products %}

                    <tr class="product-table__row">
                        <td class="d-flex flex-wrap align-items-center">
                            {% for productImage in product.photos|slice(0, 1) %}
                                <img src="{{ asset(image_directory ~ product.user.id ~ '/' ~ product.id ~ '/' ~  productImage) }}"  width="80" height="80">
                            {% endfor %}
                            <div class="preview-table__info">
                                <span>{{ product.category.name }}</span>
                                <a href="{{ path('product', {'id': product.id}) }}">{{ product.name }}</a></div>
                        </td>
                        <td class="preview-table__column"><span
                                    class="preview-table__label">Дата создания</span><span>{{ product.createdAt|date("d.m.Y  H:m") }}</span>
                        </td>
                        <td class="preview-table__column"><span
                                    class="preview-table__label">Обновлено (дн.)</span><span>{{ product.updatedAt|date("d.m.Y  H:m") }}</span>
                        </td>
                        <td>
                            {{ product.status.name }}
                        </td>
                        <td>
                            <a class="preview-table__link" href="{{ path('product_edit', {'id' : product.id}) }}">Редактировать</a>
                            <a class="preview-table__link" href="{{ path('product_delete', {'id' : product.id}) }}">/ Удалить</a>
                    </tr>

                    {% endfor %}
                    </tbody>
                    </table>
                <div class="preview-table__footer"><a class="preview-table__link" href="{{ path('dashboard_add') }}">+ Добавить
                        объявления</a>
                    <p class="link-gray">Вам доступно {{ products|length }} объявлений для бесплатного размещения</p></div>
            </div>
        </section>
    </div>
{% endblock %}

templates/dashboard/sidebar-admin.html.twig
<aside class="user__navigation"><p class="user__title title-underline"><span style="line-height: 30px">Личный кабинет администратора</span></p>
    <ul class="list list-images">
        <li class="list__item"><a href="{{ path('admin') }}">Объявления<i class="material-icons">create</i></a>
        </li>
        <li class="list__item"><a href="{{ path('admin_categories') }}">Категории</a></li>
        <li class="list__item"><a href="{{ path('admin_filters') }}">Фильтры</a></li>
        <li class="list__item"><a href="{{ path('admin_messages') }}">Сообщения</a></li>
    </ul>
</aside>